from pathlib import Path
from .tree import detect_framework

IGNORES = {
    "Flutter/Dart": ["test", "integration_test", "assets", "fonts", "ios", "android", "macos", "linux", "windows", "web", "generated"],
    "Node.js":      ["test", "tests", "__tests__", "coverage", "public", "static", "dist", "generated", "migrations", "seeds"],
    "Python":       ["tests", "test", "docs", "notebooks", "migrations", "fixtures", "static", "media"],
    "Rust":         ["tests", "benches", "examples", "target"],
    "Go":           ["testdata", "vendor", "docs", "examples"],
    "Unknown":      ["test", "tests", "docs", "examples", "fixtures"],
}

COMMENT = {
    "Flutter/Dart": "# Flutter — folders rarely relevant when debugging app logic",
    "Node.js":      "# Node.js — folders rarely relevant when debugging business logic",
    "Python":       "# Python — folders rarely relevant when debugging app logic",
    "Rust":         "# Rust — folders rarely relevant when debugging library logic",
    "Go":           "# Go — folders rarely relevant when debugging application logic",
    "Unknown":      "# Generic defaults — edit as needed",
}


def run_init(root):
    GREEN = "\033[1;32m"
    YELLOW = "\033[1;33m"
    DIM   = "\033[2m"
    RESET = "\033[0m"

    target = root / ".scopeignore"
    fw = detect_framework(root)
    entries = IGNORES.get(fw, IGNORES["Unknown"])

    # Filter to only existing dirs
    existing = [e for e in entries if (root / e).is_dir()]
    missing  = [e for e in entries if not (root / e).is_dir()]

    if target.exists():
        print(f"\n  {YELLOW}⚠ .scopeignore already exists.{RESET}")
        existing_content = target.read_text()
        new_entries = [e for e in existing if e not in existing_content]
        if not new_entries:
            print(f"  {DIM}Nothing new to add.{RESET}\n")
            return
        # Append new entries
        with target.open("a") as f:
            f.write(f"\n# Added by scopekit init ({fw})\n")
            for e in new_entries:
                f.write(f"{e}\n")
        print(f"  {GREEN}✓ Added {len(new_entries)} entries to .scopeignore{RESET}\n")
        return

    lines = [
        f"# .scopeignore — folders to always exclude from ScopeKit",
        f"# {fw} project — generated by: scopekit init",
        f"# Add any folder you never want to debug inside",
        f"",
        COMMENT[fw],
    ]
    for e in existing:
        lines.append(e)
    if missing:
        lines.append(f"")
        lines.append(f"# Not found yet — uncomment if they appear:")
        for e in missing:
            lines.append(f"# {e}")

    target.write_text("\n".join(lines) + "\n")

    print(f"\n  {GREEN}✓ Created .scopeignore for {fw}{RESET}")
    if existing:
        print(f"  {DIM}Ignored ({len(existing)}): {', '.join(existing)}{RESET}")
    print()
